[features]
seeds = false
skip-lint = false
[programs.devnet]
stake = "Ez8TA8T2rEyGjuEy6D6iY7Z7g51mPm4Zz5CRLndfbSjL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
